export const GET_TREE_STATE_REQ = 'TREE_STATE_REQ';
export const GET_TREE_STATE_RES = 'TREE_STATE_RES';
export const ADD_FACTORY_REQ = 'ADD_FACTORY_REQ';
export const ADD_FACTORY_RES = 'ADD_FACTORY_RES';
export const REMOVE_FACTORY_REQ = 'REMOVE_FACTORY_REQ';
export const REMOVE_FACTORY_RES = 'REMOVE_FACTORY_RES';
export const UPDATE_FACTORY_REQ = 'UPDATE_FACTORY_REQ';
export const UPDATE_FACTORY_RES = 'UPDATE_FACTORY_RES';
